<?php
/**
 * ChargeDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Elepay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Elepay;

use PHPUnit\Framework\TestCase;

/**
 * ChargeDtoTest Class Doc Comment
 *
 * @category    Class
 * @description 支払いオブジェクト
 * @package     Elepay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ChargeDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChargeDto"
     */
    public function testChargeDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "liveMode"
     */
    public function testPropertyLiveMode()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "paymentMethod"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "resource"
     */
    public function testPropertyResource()
    {
    }

    /**
     * Test attribute "orderNo"
     */
    public function testPropertyOrderNo()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "extra"
     */
    public function testPropertyExtra()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "clientIp"
     */
    public function testPropertyClientIp()
    {
    }

    /**
     * Test attribute "paid"
     */
    public function testPropertyPaid()
    {
    }

    /**
     * Test attribute "refunded"
     */
    public function testPropertyRefunded()
    {
    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "credential"
     */
    public function testPropertyCredential()
    {
    }

    /**
     * Test attribute "paidTime"
     */
    public function testPropertyPaidTime()
    {
    }

    /**
     * Test attribute "refundTime"
     */
    public function testPropertyRefundTime()
    {
    }

    /**
     * Test attribute "expiryTime"
     */
    public function testPropertyExpiryTime()
    {
    }

    /**
     * Test attribute "settleTime"
     */
    public function testPropertySettleTime()
    {
    }

    /**
     * Test attribute "createTime"
     */
    public function testPropertyCreateTime()
    {
    }
}
