<?php
/**
 * CodeDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Elepay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: support@elestyle.jp
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Elepay;

use PHPUnit\Framework\TestCase;

/**
 * CodeDtoTest Class Doc Comment
 *
 * @category    Class
 * @description EasyQRコードオブジェクト
 * @package     Elepay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CodeDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CodeDto"
     */
    public function testCodeDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "liveMode"
     */
    public function testPropertyLiveMode()
    {
    }

    /**
     * Test attribute "codeUrl"
     */
    public function testPropertyCodeUrl()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "orderNo"
     */
    public function testPropertyOrderNo()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "expired"
     */
    public function testPropertyExpired()
    {
    }

    /**
     * Test attribute "expiryTime"
     */
    public function testPropertyExpiryTime()
    {
    }

    /**
     * Test attribute "createTime"
     */
    public function testPropertyCreateTime()
    {
    }
}
