<?php
/**
 * PaymentMethodDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Elepay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * elepay API リファレンス
 *
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@elestyle.jp
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Elepay;

use PHPUnit\Framework\TestCase;

/**
 * PaymentMethodDtoTest Class Doc Comment
 *
 * @category    Class
 * @description 決済方法詳細情報
 * @package     Elepay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentMethodDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentMethodDto"
     */
    public function testPaymentMethodDto()
    {
    }

    /**
     * Test attribute "paymentMethod"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "resources"
     */
    public function testPropertyResources()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "ua"
     */
    public function testPropertyUa()
    {
    }

    /**
     * Test attribute "channelProperties"
     */
    public function testPropertyChannelProperties()
    {
    }
}
